In [1]:
# Standard Library
import warnings

# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore warnings
warnings.filterwarnings("ignore")

# Visualization settings
plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
df = pd.read_csv("../data/raw/train.csv")

In [3]:
df_processed = df.copy()

In [4]:
df_processed.drop(columns=["Loan_ID"], inplace=True)

In [5]:
df_processed.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
# Categorical
df_processed["Gender"] = df_processed["Gender"].fillna(df_processed["Gender"].mode()[0], inplace=True)
df_processed["Married"] = df_processed["Married"].fillna(df_processed["Married"].mode()[0], inplace=True)
df_processed["Dependents"] = df_processed["Dependents"].fillna(df_processed["Dependents"].mode()[0], inplace=True)
df_processed["Self_Employed"] = df_processed["Self_Employed"].fillna(df_processed["Self_Employed"].mode()[0], inplace=True)

# Numerical
df_processed["LoanAmount"] = df_processed["LoanAmount"].fillna(df_processed["LoanAmount"].median(), inplace=True)
df_processed["Loan_Amount_Term"] = df_processed["Loan_Amount_Term"].fillna(df_processed["Loan_Amount_Term"].median(), inplace=True)

# Binary
df_processed["Credit_History"] = df_processed["Credit_History"].fillna(df_processed["Credit_History"].mode()[0], inplace=True)

In [7]:
df_processed.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [8]:
df_processed["TotalIncome"] = (
    df_processed["ApplicantIncome"] +
    df_processed["CoapplicantIncome"]
)

In [9]:
df_processed["LoanToIncomeRatio"] = (
    df_processed["LoanAmount"] /
    (df_processed["TotalIncome"] + 1)
)

In [10]:
df_processed["Gender"] = df_processed["Gender"].map({"Male":1, "Female":0})

df_processed["Married"] = df_processed["Married"].map({"Yes":1, "No":0})

df_processed["Education"] = df_processed["Education"].map({
    "Graduate":1,
    "Not Graduate":0
})

df_processed["Self_Employed"] = df_processed["Self_Employed"].map({
    "Yes":1,
    "No":0
})

df_processed["Loan_Status"] = df_processed["Loan_Status"].map({
    "Y":1,
    "N":0
})

In [11]:
df_processed["Dependents"] = (
    df_processed["Dependents"]
    .replace("3+", 3)
    .astype(int)
)

In [12]:
df_processed = pd.get_dummies(
    df_processed,
    columns=["Property_Area"],
    drop_first=True
)

In [13]:
df_processed.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,TotalIncome,LoanToIncomeRatio,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,0,5849,0.0,128.0,360.0,1.0,1,5849.0,0.021880,False,True
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,6091.0,0.021011,False,False
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,3000.0,0.021993,False,True
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,4941.0,0.024282,False,True
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,6000.0,0.023496,False,True

In [14]:
df_processed.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   614 non-null    int64
 1   Married                  614 non-null    int64
 2   Dependents               614 non-null    int64
 3   Education                614 non-null    int64
 4   Self_Employed            614 non-null    int64
 5   ApplicantIncome          614 non-null    int64
 6   CoapplicantIncome        614 non-null    float64
 7   LoanAmount               614 non-null    float64
 8   Loan_Amount_Term         614 non-null    float64
 9   Credit_History           614 non-null    float64
 10  Loan_Status              614 non-null    int64
 11  TotalIncome              614 non-null    float64
 12  LoanToIncomeRatio        614 non-null    float64
 13  Property_Area_Semiurban  614 non-null    bool
 14  Property_Area_Urban      614 non-null    bool
dtypes: bool(2), float64(6), int64(7)
memory usage: 63.7 KB

In [15]:
df_processed.describe()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,TotalIncome,LoanToIncomeRatio
count,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000
mean,0.817590,0.653094,0.744300,0.781759,0.133550,5403.459283,1621.245798,145.752443,342.410423,0.855049,0.687296,7024.705081,0.023872
std,0.386497,0.476373,1.009623,0.413389,0.340446,6109.041673,2926.248369,84.107233,64.428629,0.352339,0.463973,6458.663872,0.008704
min,0.000000,0.000000,0.000000,0.000000,0.000000,150.000000,0.000000,9.000000,12.000000,0.000000,0.000000,1442.000000,0.002523
25%,1.000000,0.000000,0.000000,1.000000,0.000000,2877.500000,0.000000,100.250000,360.000000,1.000000,0.000000,4166.000000,0.019218
50%,1.000000,1.000000,0.000000,1.000000,0.000000,3812.500000,1188.500000,128.000000,360.000000,1.000000,1.000000,5416.500000,0.024126
75%,1.000000,1.000000,1.000000,1.000000,0.000000,5795.000000,2297.250000,164.750000,360.000000,1.000000,1.000000,7521.750000,0.028147
max,1.000000,1.000000,3.000000,1.000000,1.000000,81000.000000,41667.000000,700.000000,480.000000,1.000000,1.000000,81000.000000,0.082685

In [21]:
df_processed.to_csv(
    "../data/processed/loan_processed.csv",
    index=False
)

In [16]:
df_processed.isnull().sum()

Gender                     0
Married                    0
Dependents                 0
Education                  0
Self_Employed              0
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                 0
Loan_Amount_Term           0
Credit_History             0
Loan_Status                0
TotalIncome                0
LoanToIncomeRatio          0
Property_Area_Semiurban    0
Property_Area_Urban        0
dtype: int64

In [20]:
df_processed.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,TotalIncome,LoanToIncomeRatio,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,0,5849,0.0,128.0,360.0,1.0,1,5849.0,0.021880,False,True
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,6091.0,0.021011,False,False
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,3000.0,0.021993,False,True
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,4941.0,0.024282,False,True
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,6000.0,0.023496,False,True